export const urls = {
  usersUrl: 'api/users',
  studentAssignmentsUrl: 'api/student-assignments',
  assignmentsUrl: 'api/assignments',
  batchAssignmentUrl: 'api/batch-assignments',
  rolesUrl: 'api/roles',
  booksDataUrl: 'api/books',
  getRolesUrl: 'api/roles',
  createVmsUrl: 'api/labVms/createLabVm',
  videoDataUrl: 'api/videos',
  bookChaptersUrl: 'api/bookChapters',
  videoChaptersUrl: 'api/videoChapters/findVideoChapter',
  videoChaptersCreateUrl: 'api/videoChapters',
  presentationsUrl: 'api/presentations',
  presentationChapterUrl: 'api/presentationChapters/findPresentationChapter',
  getAzureVmsUrl: 'api/labVms',
  deletevmUrl:'delete',
  getEvents: 'api/calendarEvents',
  getCourses:'api/courss',
  getBatches:'api/cycles',
  getEnrollments:'api/enrollments',
  getTopics:'api/topics',
  presentationChaptersCreateUrl:'api/presentationChapters',
}
